services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8008:8000"
    volumes:
      - ./chroma_data:/chroma/chroma
    restart: always

networks:
  default:
    name: dupi-network
